name: CI artifacts generation

on: [push, pull_request]


jobs:

  Run-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bzip2 make u-boot-tools

    - name: Build images
      run: source .github/scripts/ci.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: uboot-linux-images
        path: |
          artifacts/*
